# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161005_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
