# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20161007_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='billing_address',
        ),
    ]
