# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20161007_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='assests/img/avatars'),
        ),
    ]
