# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 21:54
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20161007_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
